### ISSUE TITLE
failed to match matched object (wikidata is already present)

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#148]
https://osm.wikidata.link/no_match/relation/3061599 is "no match" for Q11747197 but https://osm.wikidata.link/no_match/relation/3061599 already has wikidata=Q11747197

I ordered refresh what changed nothing

**Comment by EdwardBetts** [comment]
Looks like something wrong with the updating of tags.

**Comment by matkoniecz** [comment]
https://osm.wikidata.link/no_match/way/46149647 is the next case

**Comment by EdwardBetts** [comment]
Q11747197 doesn't match match https://www.openstreetmap.org/way/298110952 because the names don't match: 'Kościół pw. św. Michała Archanioła' and 'Kościół św. Michała Archanioła w Długołęce'. I've added 'pw' to the list of terms to ignore. There needs to be some code that knows this church is in Długołęce, so it can ignore the 'w Długołęce'.

**Comment by EdwardBetts** [comment]
A refresh fixed the second example, Uluṟu-Kata Tjuṯa National Park.

**Comment by EdwardBetts** [comment]
Removing place names at the end of names didn't help the match because the places names are different. The church name has Długołęce spelt with a 'c', but village name is Długołęka, spelt with a 'k'.

**Comment by matkoniecz** [comment]
> The church name has Długołęce spelt with a 'c', but village name is Długołęka, spelt with a 'k'.

In English it would be "in Długołęka" and "Długołęka".

Unfortunately, in some languages including Polish it is not so easy. I am not sure is it feasible to support how words may change in all possible languages...
