### ISSUE TITLE
match  special airfield (Q2301048)  to aeroway=helipad

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#215]
see https://osm.wikidata.link/Q16573482 and https://www.openstreetmap.org/way/532315516

**Comment by EdwardBetts** [comment]
The matcher requires names to be the same, way/532315516 doesn't have a name, so it can't match.

**Comment by matkoniecz** [comment]
Yes, I know but it is not listing helipad in considered tags.

**Comment by EdwardBetts** [comment]
Lądowisko (Q2301048) isn't a concept we have in the English language. Wikidata is confused, it is described as "German aerodrome category", which can't be right because you have them in Poland.

I've adjusted Lądowisko Kraków-Szpital im. Rydygiera (Q16573482) on Wikidata so it is an instance of  helipad (Q534159), I'm going to add a button to refresh an individual item, so the search criteria are updated.

**Comment by matkoniecz** [comment]
Lądowisko means "helipad" (as far as I am aware).

Polish Wikipedia article is about legal term as defined in Polish law (some people love turning every definition in law into an article).
