### ISSUE TITLE
Search criteria for "basilica" in map.osm

### ISSUE THREAD

**Issue by ivanbranco** [EdwardBetts/osm-wikidata#634]
If there's a "basilica" (building type of church - istance of Q4846867) wikidata entry, the website looks for:

- Tag:amenity=fountain
- Tag:historic=memorial
- Tag:historic=monument
- Tag:tourism=artwork

While it should look for a amenity=place_of_worship, building=church or building=* in general in my opinion.

Example: https://map.osm.wikidata.link/item/Q109758161

**Comment by EdwardBetts** [comment]
It turns out there are two basilica items on Wikidata:
- https://www.wikidata.org/wiki/Q163687
- https://www.wikidata.org/wiki/Q4846867

Q4846867 has been updated to be a subclass of church, and I've refreshed it in the database behind OWL Map. The tags considered are now:

- Key:building
- Key:building:levels
- Tag:amenity=place_of_worship
- Tag:building=church
- Tag:building=yes
- Tag:religion=christian
