### ISSUE TITLE
Move OSM authentication to OAuth 2.0

### ISSUE THREAD

**Issue by pnorman** [EdwardBetts/osm-wikidata#656]
OAuth 1.0a is deprecated, and programs which use it to authenticate requests to OpenStreetMap should move to OAuth 2.0. A date has not yet been set for turning off OAuth 1.0a and HTTP Basic.

It's best to move to OAuth 2.0 well in advance of any turn-off, because users may take some time to upgrade software and to re-authenticate.

See https://github.com/openstreetmap/operations/issues/867 for details.

**Comment by n1ngu** [comment]
The least effort path forward might be resolving https://github.com/python-social-auth/social-core/issues/758, then just use the new social auth backend.

Otherwise, this could mean finding a different authentication plugin.

**Comment by EdwardBetts** [comment]
I'll work on this.

**Comment by EdwardBetts** [comment]
I'd like to clarify that the OSM Wikidata matcher does not currently use an OAuth library for authentication. A few years ago, a deliberate decision was made to move away from using `python-social-auth` for OAuth integration due to certain limitations and considerations specific to our project.

Sorry if the documentation is out of date.

**Comment by EdwardBetts** [comment]
I take that back. I'm using the requests-oauthlib Python library.

**Comment by danieldegroot2** [comment]
https://github.com/EdwardBetts/osm-wikidata/blob/2a5ace3e123e47d09ec8dddecf176764c72d2ce5/matcher/osm_oauth.py#L12

Note, `api.openstreetmap.org` API url currently can not do OAuth 2 handshake. See https://github.com/openstreetmap/operations/issues/951
You can split the `www.` base URL and `api.` API url. See https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

cc: @EdwardBetts

**Comment by n1ngu** [comment]
> A few years ago, a deliberate decision was made to move away from using `python-social-auth` for OAuth integration due to certain limitations and considerations specific to our project.

Passing-by to record that OSM-OAuth2 support has been recently merged into `python-social-auth` (see https://github.com/python-social-auth/social-core/pull/877)

Out of curiosity, which were those project-specific limitations that made `python-social-auth` unsuitable? If you could point me into the right PRs/issues/commits I'd be happy to check them myself. Just asking because you may want to revisit those now that `python-social-auth` could save you from maintaining the auth backend.

**Comment by EdwardBetts** [comment]
@n1ngu Thanks for your comment!

I don't remember what problem I had with `python-social-auth`.

I'll take another look.
